### ISSUE TITLE
tbl_df causing errors from encode(sf)

### ISSUE THREAD

**Issue by SymbolixAU** [SymbolixAU/googlePolylines#16]
This comes from `sf::read_sf("/sf/file/.shp")`, which builds it using a tibble.

But, `sf::st_read()` is fine...

---

TODO

- [x] test on [googleway](https://github.com/SymbolixAU/googlePolylines/issues/16#issuecomment-414188344) 
- [x] test on mapdeck
- [x] include a test for custom classes (and tibble!)

**Comment by mdsumner** [comment]
Just to note that `read_sf` also defaults to `stringsAsFactors = FALSE` (mainly why I use it), and  can be passed to `st_read` for a vanilla data.frame with character vars.

Most problems I see with tibbles are about [,1] being assumed to `drop = TRUE` for a vanilla data frame.

**Comment by SymbolixAU** [comment]
@mdsumner timely response; I've just been reading the various discussions on `r-spatial/sf` about this. 

I don't think this will be a difficult solve, just need to get motivated to do it. Mainly because all my work is in `data.table` and not the `tidyverse`.

**Comment by mdsumner** [comment]
Cool, didn't think I had much to add - just making sure. It's clarified and galvanized somewhat for me in the last couple of years ;)  

I wasn't thinking of `data.table`, so appreciate hearing that that impacts your views. I need to be more aware of its relationships here.

**Comment by SymbolixAU** [comment]
Likewise; I need to be more aware of what the rest of the world use :)

**Comment by SymbolixAU** [comment]
fix is inbound on branch `tbldf`

```
library(sf)
library(googlePolylines)

df_nc <- sf::st_read(system.file("shape/nc.shp", package="sf"))
tbl_nc <- sf::read_sf(system.file("shape/nc.shp", package="sf"))

enc_nc <- encode(df_nc)
enc_tbl <- encode(tbl_nc)
enc_tbl_lite <- encode(tbl_nc, strip = T)

attr(enc_nc, 'class')
attr(enc_tbl, 'class')
attr(enc_tbl_lite, 'class')

attr(enc_nc[1, ], 'class')
attr(enc_tbl[1, ], 'class')

library(googleway)

set_key("GOOGLE_MAP_KEY")

google_map() %>%
  add_polygons(data = df_nc)

google_map() %>%
  add_polygons(data = tbl_nc)
```
