### ISSUE TITLE
Refactor encode() Rcpp code

### ISSUE THREAD

**Issue by ChrisMuir** [SymbolixAU/googlePolylines#36]
Hey, so I worked some on edits to the Rcpp functions related to `encode()`, trying to squeeze more speed out of them. I made some minor changes and got ~40% speed up in the benchmarks below. Most of the changes are just building `std` vectors in a namespace that get over-written in each loop, as opposed to creating multiple `NumericVector`s in each loop iteration. Per usual, all tests are passing locally.

I wanted to bring this up here because my one open [pr](https://github.com/SymbolixAU/googlePolylines/pull/35) is already getting a little overgrown. Let me know if you're interested, I can either push to the open PR, or wait and open a new one later.

## Benchmarks

I have no idea if these tests are representative of common use, I essentially lifted them from `test-Encode.R` and just made the polygon list longer (100,000 elements).

### polygons

```r
library(googlePolylines)
library(sf)
polygon <- sf::st_sfc(sf::st_polygon(
  list(matrix(c(144, 144.1, 144.2, 144, -37, -37.1, -37.2, -37), ncol = 2))))
polygon <- rep(polygon, 100000)
```
Original code
```r
microbenchmark::microbenchmark(encode(polygon), times = 10)
#> Unit: milliseconds
#>             expr     min       lq     mean   median       uq     max neval
#> encode(polygon) 388.162 389.4418 439.4863 450.9892 465.9901 489.101    10
```
Updated code
```r
microbenchmark::microbenchmark(encode(polygon), times = 10)
#> Unit: milliseconds
#>             expr      min      lq     mean   median       uq      max neval
#> encode(polygon) 281.2151 292.136 300.4025 299.5898 303.0663 323.9693    10
```

### multipolygons
```r
library(googlePolylines)
library(sf)
sf <- sf::st_sf(geo = polygon)
m1 <- matrix(c(144, 144.1, 144.2, 144, -37, -37.1, -37.2, -37), ncol = 2)
m2 <- m1 + 1
multipolygon <- sf::st_sfc(sf::st_multipolygon(list(list(m1, m2))))
multipolygon <- rep(multipolygon, 100000)
```
Original code
```r
microbenchmark::microbenchmark(encode(multipolygon), times = 10)
#> Unit: milliseconds
#>                  expr     min     lq     mean   median       uq      max neval
#> encode(multipolygon) 638.299 657.18 707.6419 720.7405 744.7296 769.4089    10
```
Updated code
```r
microbenchmark::microbenchmark(encode(multipolygon), times = 10)
#> Unit: milliseconds
#>                  expr      min       lq     mean   median       uq      max neval
#> encode(multipolygon) 432.4685 446.4945 464.7041 451.4713 464.8576 540.8584    10
```

**Comment by SymbolixAU** [comment]
Awesome stuff. 

Can you please open a new PR (for no particular reason, just seems logical to keep the `decode()` and `encode()` PRs separate)

**Comment by ChrisMuir** [comment]
Cool, sounds good and will do. Still tweaking a few things, but should have things done in a day or two.

**Comment by ChrisMuir** [comment]
Okay, so this may end up taking longer than I thought....I ran into git issues tonight, and my wife and I are moving this weekend, so I probably won't be able to do anything with this until after the move and we're settled in, so will probably be late next week.

To summarize the git issues, I created a new branch for the new pull request, [rcpp_encode_refactor](https://github.com/ChrisMuir/googlePolylines/tree/rcpp_encode_refactor), added your repo as a remote, and tried to rebase to your repo's upstream master. However, when pushing my newest edits to my new branch on GitHub, I see that the new branch still has all four commits I made earlier this week. and if I try to open a new PR, it also contains all four commits from my original PR.

Not sure what to do with this other than creating another new branch and trying again. Also, if you were to merge my original pull request, I don't know what effect that would have on my new branch.

Sorry for all the troubles....sometimes git is hard 😄

**Comment by SymbolixAU** [comment]
ha - been there!

Would it help if I first merged your original PR over the weekend?

**Comment by ChrisMuir** [comment]
Yeah, I mean, in theory if you were to merge the original PR, then a new PR from my new branch should only contain my latest commit.

And if you want edits/changes to the original PR, please don't hesitate to ask, the master branch of my fork is free of the `encode()` refactor edits/commit, so I'd be able to push any follow up edits from master to the original PR.

Thanks!

**Comment by ChrisMuir** [comment]
Also, one last question....in the file `encode.cpp`, there's a bunch of code related to objects that have Z & M attributes that is commented out (see `encode_vector()` example below). Do you want me to update that code to be compatible with the new code that I added (while still leaving it commented out)?

```cpp
void encode_vector( std::ostringstream& os, std::ostringstream& oszm, Rcpp::List vec, Rcpp::CharacterVector& sfg_dim,
                    int dim_divisor) {

  // - XY == [0][1]
  // - XYZ == [0][1][2]{3}
  // - XYM == [0][1][2]{3}
  // - XYZM == [0][1][2][3]
  
  int n = vec.size() / dim_divisor;
  
  global_vars::lats.clear();
  global_vars::lons.clear();
  
  for (int i = 0; i < n; i++) {
    global_vars::lons.push_back(vec[i]);
    global_vars::lats.push_back(vec[(i + n)]);
  }
  
  global_vars::encodedString = encode_polyline();
  addToStream(os);
  
  // if (dim_divisor > 2) {
  //   // there are Z and M attributes to encode
  //   // constructor sets them to 0
  //   Rcpp::NumericVector elev(n);
  //   Rcpp::NumericVector meas(n);
  //   
  //   for (int i = 0; i < n; i++) {
  //     elev[i] = vec[(i + n + n)];
  //     meas[i] = dim_divisor == 4 ? vec[(i + n + n + n)] : 0;
  //   }
  //   encodedString = encode_polyline(elev, meas);
  //   addToStream(oszm, encodedString);
  // }
  
}
```

**Comment by SymbolixAU** [comment]
no you can leave / ignore that - it's not correct. I was going to re-do the `Z/M` stuff.

**Comment by SymbolixAU** [comment]
Merged both PRs, and [added you as a contributor](https://github.com/SymbolixAU/googlePolylines/blob/master/DESCRIPTION#L9). 

Are you happy to close this issue, or is there more to come?

**Comment by ChrisMuir** [comment]
Cool, and thanks for adding me as a contributor!

Nope that's all I have for now. I enjoyed working on this quite a bit, thanks for letting me contribute 👍

**Comment by SymbolixAU** [comment]
no no, thank you!

and a bit of advertising for your work :) https://twitter.com/symbolixAU/status/1045537693915000832

**Comment by ChrisMuir** [comment]
Woah that's super cool! Thanks for the shout out!
