### ISSUE TITLE
decode always prints the input

### ISSUE THREAD

**Issue by mem48** [SymbolixAU/googlePolylines#48]
I updated to the latest version of `googlePolylines` and now `decode` always prints the input character string.

For example:

```
input <- "ohlbDnbmhN~suq@am{tAw`qsAeyhGvkz`@fge}A"
output <- googlePolylines::decode(input)
"ohlbDnbmhN~suq@am{tAw`qsAeyhGvkz`@fge}A"
```
This is not a problem for a single line, but when you parse lots of lines it fills the consol with text.

**Comment by dcooley** [comment]
argh - sorry, don't know how I missed this. I'll get the fix update don CRAN ASAP.

**Comment by dcooley** [comment]
now on CRAN
