### ISSUE TITLE
Longitude off by a factor of 10?

### ISSUE THREAD

**Issue by Robinlovelace** [SymbolixAU/googlePolylines#51]
Hi @dcooley, I'm not sure why this happened and cannot see anything in the code, but heads-up that when decoding a polyline from Valhalla the lon axis was 10x more than what it should have been:

Someone kindly pointed this out and I've just merged their PR: https://github.com/Robinlovelace/rvalhalla/pull/3/files

I imagine this is due to Valhalla's version, which does do something with "10" from the docs but not sure what: https://valhalla.github.io/valhalla/decoding/ 

This is most likely a non-issue that can just be closed but heads-up in case of use/interest.

**Comment by dcooley** [comment]
Thanks for the tip @Robinlovelace 

---

If we take their example polyline from their [api docs](https://github.com/valhalla/valhalla/blob/52d6ca708a6de72b63979b0e767e7ecc189fdb17/docs/docs/api/elevation/api-reference.md#use-an-encoded-polyline-for-input-locations)


```r
p <- "s{cplAfiz{pCa]xBxBx`AhC|gApBrz@{[hBsZhB_c@rFodDbRaG\\ypAfDec@l@mrBnHg|@?}TzAia@dFw^xKqWhNe^hWegBfvAcGpG{dAdy@_`CpoBqGfC_SnI{KrFgx@?ofA_Tus@c[qfAgw@s_Agc@}^}JcF{@_Dz@eFfEsArEs@pHm@pg@wDpkEx\\vjT}Djj@eUppAeKzj@eZpuE_IxaIcF~|@cBngJiMjj@_I`HwXlJuO^kKj@gJkAeaBy`AgNoHwDkAeELwD|@uDfC_i@bq@mOjUaCvDqBrEcAbGWbG|@jVd@rPkAbGsAfDqBvCaIrFsP~RoNjWajBlnD{OtZoNfXyBtE{B~HyAtEsFhL_DvDsGrF_I`HwDpGoH|T_IzLaMzKuOrFqfAbPwCl@_h@fN}OnI"
```
It is indeed off by *10

```r
d <- googlePolylines::decode(p)[[1]]

head( d )
# lat       lon
# 1 406.5121 -764.9449
# 2 406.5169 -764.9456
# 3 406.5163 -764.9561
# 4 406.5156 -764.9678
# 5 406.5150 -764.9774
# 6 406.5197 -764.9779
```

If you put that same polyilne into their [online demo](https://valhalla.github.io/demos/polyline/), for it to work you have to select the `polyline6` checkbox.

However, their [docs](https://github.com/valhalla/valhalla/blob/52d6ca708a6de72b63979b0e767e7ecc189fdb17/docs/docs/api/elevation/api-reference.md#use-an-encoded-polyline-for-input-locations) also say 

> `shape_format` 

> `polyline6` or `polyline5`. Specifies whether the polyline is encoded with 6 digit precision (polyline6) or 5 digit precision (polyline5). If `shape_format` is not specified, the encoded polyline is expected to be 6 digit precision.

So by default they expect `polyline6` polylines. 

And all their [decoding code examples](https://valhalla.github.io/valhalla/decoding/#c-11) have a final ` / 1000000` step. Whereas the Google standard is `/ 100000`

I really understand why they introduce this extra factor. But this is definitely something they've introduced into their code and I don't think I need to worry about it here.

---

```r
( e <- googlePolylines::encode(d / 10) )

googlePolylines::decode(e)[[1]] |> head()

# lat       lon
# 1 40.65120 -76.49449
# 2 40.65168 -76.49454
# 3 40.65162 -76.49561
# 4 40.65155 -76.49678
# 5 40.65150 -76.49773
# 6 40.65196 -76.49779
```

**Comment by Robinlovelace** [comment]
Awesome, thanks for the detailed description and good to know there was as reason for it on their side.
