### ISSUE TITLE
Removal from CRAN

### ISSUE THREAD

**Issue by mem48** [SymbolixAU/googlePolylines#52]
Hi, I've had an email from CRAN that my package (opentripplanner) will be removed because it depends on googlePolylines.

I can see the error only applies to clang on Linux. https://cran.r-project.org/web/checks/check_results_googlePolylines.html

Is there a plan to fix this before the CRAN deadline of 2024-10-24? Otherwise, I'll start looking for an alternative.

**Comment by mem48** [comment]
The specific error is;

```
/home/hornik/tmp/R.check/r-devel-clang/Work/build/Packages/BH/include/boost/qvm/quat_traits.hpp:82:30: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
   82 |     quat_traits<Q>::template write_element_idx(i, q) = s;
      |                              ^
/home/hornik/tmp/R.check/r-devel-clang/Work/build/Packages/BH/include/boost/qvm/quat_traits.hpp:92:30: error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]
   92 |     quat_traits<Q>::template write_element_idx(i, q, s);
      |                              ^
2 errors generated.
```

**Comment by rCarto** [comment]
Hi,
I hope that `googlePolylines` will get an update soon. Its use in `osrm` has been a clear improvement in speed.

If it's not fixed, we will revert to using [`gepaf`](https://cran.r-project.org/web/packages/gepaf/) for the `osrm` package.
`gepaf` is lightweight but very slow compared to `googlePolylines` (see this issue: https://github.com/riatelab/osrm/issues/71).  This solution is therefore not ideal.

My colleague @mthh is currently developing a package that uses Rust to perform the same tasks ([gepafer](https://github.com/mthh/gepafer)). It's already working properly and it's fast :rocket: , but we haven't yet undertaken to publish it on CRAN (and in all probability it won't be before October 24).

**Comment by dcooley** [comment]
Hi @rCarto and @mem48  - thanks for posting; I've just got back from a 2 week vaction and haven't been responding to any mesages :) 

but rest assured I'm aware of this and have [been working / planning](https://github.com/eddelbuettel/bh/issues/101#issuecomment-2359583289) on implementing a fix before the deadline.

**Comment by dcooley** [comment]
I've removed the BH CRAN dependency and added all the headers as local files.

- included the [qvm fix](https://github.com/boostorg/qvm/issues/54#issuecomment-2362352142)
- renamed some file names within the 100 char limit required by CRAN.

**Comment by dcooley** [comment]
on CRAN
